### ISSUE TITLE
Window OS bug, can't import fcntl

### ISSUE THREAD

**Issue by DougRzz** [vaexio/vaex#93]
Hi,

**OS: Windows 10.**   

I have encountered a bug.  When I open a hdf file, using vaex.open('myfile.hdf'), I get the error message below.  When I comment out the line 'import fcntl' in dataset_mmap.py , the issue goes away with no noticeable effect.   The fcntl module does not work on Windows, see https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows.

ERROR:MainThread:vaex:error opening 'C:\\myfile.hdf'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-140-b984d6ab4edc> in <module>()
----> 1 dataVX = vx.open(VXfiles_df.iloc[num]['path'])

~\AppData\Local\Continuum\anaconda3\lib\site-packages\vaex\__init__.py in open(path, convert, shuffle, copy_index, *args, **kwargs)
    157             return vaex.distributed.open(path, *args, **kwargs)
    158         else:
--> 159             import vaex.file
    160             import glob
    161             # sort to get predicatable behaviour (useful for testing)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\vaex\file\__init__.py in <module>()
      3 logger = logging.getLogger("vaex.file")
      4 
----> 5 import vaex.file.other
      6 try:
      7         import vaex.hdf5 as hdf5

~\AppData\Local\Continuum\anaconda3\lib\site-packages\vaex\file\other.py in <module>()
     24 from vaex.expression import Expression
     25 
---> 26 from vaex.dataset_mmap import DatasetMemoryMapped
     27 
     28 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\vaex\dataset_mmap.py in <module>()
     21 from vaex.expression import Expression
     22 import struct
---> 23 import fcntl
     24 
     25 logger = logging.getLogger("vaex.file")

ModuleNotFoundError: No module named 'fcntl'

**Comment by tsloan1377** [comment]
I have the same problem in Windows10 related to not having fcntl.
The error: ModuleNotFoundError: No module named 'fcntl'
occurs where I have tried using the example dataset with

ds = vaex.example() 

or trying with a pandas dataframe loaded previously:

ds = vaex.from_pandas(df)

I would add that I originally tried inside a conda virtualenv, then later reverted to installing via pip and retrying, the error happens in either case.

**Comment by maartenbreddels** [comment]
Thanks for letting me know. This should be fixed actually.
I'd say, try removing all vaex packages, and try with a clean slate, and maybe with a specific version number, like:
```
pip install -c vaex-core=0.6 vaex-hdf5 vaex-viz
```
Let me know if this helps (for conda install the same)

**Comment by YuanBLQ** [comment]
@tsloan1377 hey man, it's silly to ask you that how to install vaex in windows. 
I have already installed Microsoft Visual C++ 14.0 in this way: https://www.scivision.dev/python-windows-visual-c-14-required/, but it was still failed when install vaex with `pip install --pre vaex`.
here is the error log:
```
error: command 'C:\\Program Files (x86)\\Microsoft Visual 
Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\
bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "d:\pyenv\lc\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users
\\LIFECY~1\\AppData\\Local\\Temp\\pip-install-5h_ydzih\\vaex-core\\setup.py';
f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');
f.close();exec(compile(code, __file__, 'exec'))" install --recordC:\Users
\LIFECY~1\AppData\Local\Temp\pip-record-incwumv6\
install-record.txt --single-version-externally-managed --compile --install-headers 
d:\pyenv\lc\include\site\python3.6\vaex-core" failed with error code 1 in 
C:\Users\LIFECY~1\AppData\Local\Temp\pip-install-5h_ydzih\vaex-core\
```

it's glad to hear from you :)
